# Generated by Django 5.1.6 on 2025-02-12 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frente_caixa', '0002_carrinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='data_venda',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frente_caixa.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frente_caixa.venda')),
            ],
        ),
        migrations.DeleteModel(
            name='Carrinho',
        ),
    ]
